from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from colin_dot_com.views import base, signup, landing, company, message, photo, designer

urlpatterns = [
    url(r'^$', landing.landing, name='index'),
    url(r'^companies/$', company.list_companies, name='list_companies'),
    url(r'^companies/(?P<company_id>[0-9]+)/$', company.show, name='show_company'),
    url(
        "^login/$",
        auth_views.login,
        {'template_name': 'colin_dot_com/login.html'},
        name="login",
    ),
    url("^logout/$",
        auth_views.logout,
        {'template_name': 'colin_dot_com/landing/logout.html'},
        name="logout",
    ),
    url("^change_password/$",
        auth_views.password_change,
        {'template_name': 'colin_dot_com/password_change.html'},
        name="password_change",
    ),
    url("^password_change_done/$",
        auth_views.password_change_done,
        {'template_name': 'colin_dot_com/landing/password_change_done.html'},
        name="password_change_done"
    ),
    url("^invite/$", signup.signup, name="signup"),
    url("^dashboard/$", base.dashboard, name='dashboard'),
    url("^find/$", company.find, name="find"),
    url("^send_message/$", message.send, name="send_message"),
    url("^photos/find/(?P<query>.+)/$", photo.find, name="find_photo"),
    url("^photos/find/$", photo.find, name="find_photo_empty"),
    url("^messages/$", message.list_messages, name="list_messages"),
    url("^messages/(?P<message_id>[0-9]+)/$", message.view, name="view_message"),
    url("^messages/(?P<type>.+)/$", message.list_messages, name="list_messages"),
    url("^unread_messages/$", message.get_unread_messages, name="get_unread_messages"),
    url("^manifesto/$", base.manifesto, name="manifesto"),
    url("^explore/$", base.dashboard, name="list_companies"),
    url("^set_default_image/(?P<image_id>[0-9]+)/$", company.set_default_image, name="set_default_image"),
    url("^account/$", company.show, name="account"),
    url("^username/is_available/$", signup.is_available, name="is_available"),
    url('^landing/$', landing.landing, name="landing"),
    url('^preview/(?P<company_id>[0-9]+)/$', company.show, {'preview': True}, name="show_preview"),
    url('^test_send_mail/$', base.send_test_mail, name="test_send"),
    url('^signup/designer/$', designer.signup, name="designer_sign_up"),
    url('^update_company_field/$', company.update_field, name="update_company"),
    url('^update_company/$', company.update, name="update_company"),
    url('^add_photo/(?P<company_id>[0-9]+)/$', photo.add, name="add_photo"),
    url('^designers/(?P<designer_id>.+)/$', designer.show, name="designer_profile"),
    url('^api/conversations/$', message.get_conversations, name="list_conversations"),
    url('^api/conversations/(?P<friend_id>[0-9]+)/$', message.get_convo_items, name="list_conversations"),
    url('^api/send_message/$', message.send, {'format': 'json'}, name="send_message_json"),
    url('^add_attachment/$', message.add_attachment, name="add_attachment"),
    url('^api/read_message/$', message.read, name="read_message"),
    url('^delete_photo/(?P<photo_id>.+)/$', photo.delete, name="delete_photo"),
    url('^deactivate_account/(?P<user_id>.+)/$', base.deactivate, name="delete_photo"),

]
