# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(verbose_name='date_added')),
                ('blurb', models.CharField(default='', max_length=250)),
                ('address_line_1', models.CharField(default='', max_length=1000)),
                ('address_line_2', models.CharField(default='', max_length=1000)),
                ('logo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('caption', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
                ('description', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, default='0000.00', max_digits=6)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('short_url', models.CharField(max_length=200, null=True, unique=True)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='colin_dot_com.Color')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='colin_dot_com.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='colin_dot_com.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ShortSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='short_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='colin_dot_com.ShortSize'),
        ),
        migrations.AddField(
            model_name='photo',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='colin_dot_com.Project'),
        ),
        migrations.AddField(
            model_name='material',
            name='tags',
            field=models.ManyToManyField(blank=True, to='colin_dot_com.MaterialTag'),
        ),
    ]
