# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colin_dot_com', '0002_company_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='comment',
        ),
    ]
