# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-24 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colin_dot_com', '0009_auto_20160923_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
