# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-24 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colin_dot_com', '0010_auto_20160924_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='zip',
            field=models.CharField(default='', max_length=5),
        ),
    ]
