# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-24 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colin_dot_com', '0011_company_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address_line_1',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='company',
            name='zip',
            field=models.CharField(blank='True', default='', max_length=5),
        ),
    ]
