# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colin_dot_com', '0013_company_material_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Instagram Handle'),
        ),
    ]
