# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colin_dot_com', '0017_auto_20161012_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='colin_dot_com.MessageAttachment'),
        ),
    ]
