# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colin_dot_com', '0018_auto_20161012_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='attachments',
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='colin_dot_com.Message'),
        ),
    ]
