# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colin_dot_com', '0019_auto_20161012_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_read',
            field=models.DateField(blank=True, null=True),
        ),
    ]
