# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colin_dot_com', '0021_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='in_reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='colin_dot_com.Message'),
        ),
    ]
