# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colin_dot_com', '0022_message_in_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='blurb',
            field=models.TextField(default='', max_length=250),
        ),
    ]
