# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colin_dot_com', '0023_auto_20161012_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thread_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
