# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-17 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colin_dot_com', '0025_auto_20161016_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_image',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
