# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-18 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colin_dot_com', '0026_company_default_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
