# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-14 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colin_dot_com', '0030_auto_20170105_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
