# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-14 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colin_dot_com', '0031_message_email_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='send_email_notification',
            field=models.BooleanField(default=False),
        ),
    ]
