# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-11 18:19
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('colin_dot_com', '0042_auto_20170307_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to=''),
        ),
    ]
