# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-11 18:22
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('colin_dot_com', '0043_auto_20170311_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=''),
        ),
    ]
